using System;
using System.Collections.Generic;

#nullable disable

namespace NHRM_Admin_API.Model
{
    public partial class PatientMeasurement
    {
        public int MeasurementId { get; set; }
        public int CategoryId { get; set; }
        public string Urnumber { get; set; }
        public int Frequency { get; set; }
        public DateTime FrequencySetDate { get; set; }

        
        public PatientMeasurement(int measurementId, int categoryId, string urnumber, int frequency, DateTime frequencySetDate)
        {
            MeasurementId = measurementId;
            CategoryId = categoryId;
            Urnumber = urnumber;
            Frequency = frequency;
            FrequencySetDate = frequencySetDate;
        }

        public PatientMeasurement()
        {
            MeasurementRecords = new HashSet<MeasurementRecord>();
        }

        // Data related to the PatientMeasurement table, generated by efcore

        public virtual Measurement Measurement { get; set; }
        public virtual PatientCategory PatientCategory { get; set; }
        public virtual ICollection<MeasurementRecord> MeasurementRecords { get; set; }
    }
}
